# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# History-mode SPA rewrite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"